import React from "react"
import { Metadata } from "next"
// export const metadata = {
//   title : "Next.js",
//   description : "Generated by Next.js"
// }



export const metadata : Metadata = {
    title  : {
        default : "Vijaysinh in main layout.tsx",
        template : "%s | nextjs learning",
        
    },
    description : "Generated by nextJs"
}
export default function LayoutFunction({
    children
} : {
    children : React.ReactNode
}){
    return(
         <html>
                <body>
                      { children }
                </body>
         </html>
    )
}